<?php

namespace App\Http\Controllers;

use App\Models\Medicine;
use Illuminate\Support\Collection;
use Illuminate\View\View;

class WelcomeController extends Controller
{
    /**
     * Display the public landing page (hero + chatbot + features).
     */
    public function index(): View
    {
        $medicines = $this->mappedMedicines();

        return view('welcome', compact('medicines'));
    }

    /**
     * Display the medicine storefront page.
     */
    public function medicines(): View
    {
        $medicines = $this->mappedMedicines();

        return view('medicines', compact('medicines'));
    }

    /**
     * Return a mapped collection of medicines with stock info.
     *
     * @return Collection<int, array<string, mixed>>
     */
    private function mappedMedicines(): Collection
    {
        $dbMedicines = Medicine::with('stockBatches')->get();

        $figmaCatalog = [
            // IV Fluids
            [
                'id' => 1,
                'name' => 'Normal Saline 0.9% 1L',
                'generic_name' => 'Sodium Chloride 0.9%',
                'brand' => 'Baxter',
                'category' => 'IV Fluids',
                'unit_price' => 85.00,
                'original_price' => null,
                'unit' => 'bag',
                'available_stock' => 300,
                'description' => 'Isotonic crystalloid solution for fluid and electrolyte replenishment.',
                'rx' => true,
                'badge' => null,
                'rating' => 4.9,
                'sold' => 540,
            ],
            [
                'id' => 2,
                'name' => 'D5W (Dextrose 5%) 1L',
                'generic_name' => 'Dextrose in Water 5%',
                'brand' => 'Baxter',
                'category' => 'IV Fluids',
                'unit_price' => 80.00,
                'original_price' => null,
                'unit' => 'bag',
                'available_stock' => 280,
                'description' => '5% dextrose in water for caloric supplementation and fluid replacement.',
                'rx' => true,
                'badge' => null,
                'rating' => 4.8,
                'sold' => 410,
            ],
            [
                'id' => 3,
                'name' => "Lactated Ringer's 1L",
                'generic_name' => "Lactated Ringer's Solution",
                'brand' => 'Baxter',
                'category' => 'IV Fluids',
                'unit_price' => 95.00,
                'original_price' => null,
                'unit' => 'bag',
                'available_stock' => 200,
                'description' => 'Balanced crystalloid solution for surgical and trauma fluid resuscitation.',
                'rx' => true,
                'badge' => null,
                'rating' => 4.9,
                'sold' => 320,
            ],
            [
                'id' => 4,
                'name' => 'D5NM (Dextrose in NaCl) 1L',
                'generic_name' => 'Dextrose with Sodium Chloride',
                'brand' => 'Otsuka',
                'category' => 'IV Fluids',
                'unit_price' => 90.00,
                'original_price' => null,
                'unit' => 'bag',
                'available_stock' => 150,
                'description' => 'Maintenance fluid combining dextrose and sodium chloride.',
                'rx' => true,
                'badge' => null,
                'rating' => 4.7,
                'sold' => 210,
            ],
            // Injectables
            [
                'id' => 5,
                'name' => 'Ceftriaxone 1g IV',
                'generic_name' => 'Ceftriaxone Sodium',
                'brand' => 'Mediphil',
                'category' => 'Injectables',
                'unit_price' => 120.00,
                'original_price' => 145.00,
                'unit' => 'vial',
                'available_stock' => 180,
                'description' => 'Third-generation cephalosporin for severe bacterial infections.',
                'rx' => true,
                'badge' => 'SALE',
                'rating' => 4.9,
                'sold' => 290,
            ],
            [
                'id' => 6,
                'name' => 'Ampicillin 500mg IV',
                'generic_name' => 'Ampicillin Sodium',
                'brand' => 'Mediphil',
                'category' => 'Injectables',
                'unit_price' => 55.00,
                'original_price' => null,
                'unit' => 'vial',
                'available_stock' => 160,
                'description' => 'Broad-spectrum penicillin antibiotic for serious infections.',
                'rx' => true,
                'badge' => null,
                'rating' => 4.7,
                'sold' => 175,
            ],
            [
                'id' => 7,
                'name' => 'Hydrocortisone 100mg IV',
                'generic_name' => 'Hydrocortisone Sodium Succinate',
                'brand' => 'Pharex',
                'category' => 'Injectables',
                'unit_price' => 95.00,
                'original_price' => null,
                'unit' => 'vial',
                'available_stock' => 90,
                'description' => 'Corticosteroid for severe allergic reactions and adrenal insufficiency.',
                'rx' => true,
                'badge' => null,
                'rating' => 4.8,
                'sold' => 130,
            ],
            [
                'id' => 8,
                'name' => 'Metoclopramide 10mg IV',
                'generic_name' => 'Metoclopramide HCl',
                'brand' => 'Pharex',
                'category' => 'Injectables',
                'unit_price' => 38.00,
                'original_price' => null,
                'unit' => 'amp',
                'available_stock' => 220,
                'description' => 'Antiemetic for nausea and vomiting management.',
                'rx' => true,
                'badge' => null,
                'rating' => 4.6,
                'sold' => 340,
            ],
            [
                'id' => 9,
                'name' => 'Epinephrine 1mg/mL',
                'generic_name' => 'Epinephrine HCl',
                'brand' => 'Hospira',
                'category' => 'Injectables',
                'unit_price' => 75.00,
                'original_price' => null,
                'unit' => 'amp',
                'available_stock' => 60,
                'description' => 'Emergency use for anaphylaxis and cardiac arrest.',
                'rx' => true,
                'badge' => 'CRIT',
                'rating' => 4.9,
                'sold' => 80,
            ],
            [
                'id' => 10,
                'name' => 'Atropine Sulfate 1mg/mL',
                'generic_name' => 'Atropine Sulfate',
                'brand' => 'Hospira',
                'category' => 'Injectables',
                'unit_price' => 65.00,
                'original_price' => null,
                'unit' => 'amp',
                'available_stock' => 55,
                'description' => 'Anticholinergic for bradycardia and organophosphate poisoning.',
                'rx' => true,
                'badge' => 'CRIT',
                'rating' => 4.8,
                'sold' => 65,
            ],
            [
                'id' => 11,
                'name' => 'Furosemide 20mg IV',
                'generic_name' => 'Furosemide',
                'brand' => 'Pharex',
                'category' => 'Injectables',
                'unit_price' => 42.00,
                'original_price' => null,
                'unit' => 'amp',
                'available_stock' => 140,
                'description' => 'Loop diuretic for edema and acute pulmonary edema.',
                'rx' => true,
                'badge' => null,
                'rating' => 4.7,
                'sold' => 195,
            ],
            // Oral Medications
            [
                'id' => 12,
                'name' => 'Amoxicillin 500mg Cap',
                'generic_name' => 'Amoxicillin',
                'brand' => 'Pharex',
                'category' => 'Oral Medications',
                'unit_price' => 12.00,
                'original_price' => null,
                'unit' => 'capsule',
                'available_stock' => 500,
                'description' => 'Broad-spectrum oral antibiotic for common bacterial infections.',
                'rx' => true,
                'badge' => null,
                'rating' => 4.8,
                'sold' => 620,
            ],
            [
                'id' => 13,
                'name' => 'Paracetamol 500mg Tab',
                'generic_name' => 'Paracetamol',
                'brand' => 'Biogesic',
                'category' => 'Oral Medications',
                'unit_price' => 5.00,
                'original_price' => 7.00,
                'unit' => 'tablet',
                'available_stock' => 900,
                'description' => 'Analgesic and antipyretic for pain and fever relief.',
                'rx' => false,
                'badge' => 'SALE',
                'rating' => 4.9,
                'sold' => 1400,
            ],
            [
                'id' => 14,
                'name' => 'Omeprazole 20mg Cap',
                'generic_name' => 'Omeprazole',
                'brand' => 'Pharex',
                'category' => 'Oral Medications',
                'unit_price' => 18.00,
                'original_price' => null,
                'unit' => 'capsule',
                'available_stock' => 350,
                'description' => 'Proton pump inhibitor for peptic ulcers and GERD.',
                'rx' => false,
                'badge' => null,
                'rating' => 4.7,
                'sold' => 480,
            ],
            [
                'id' => 15,
                'name' => 'Amlodipine 5mg Tab',
                'generic_name' => 'Amlodipine Besylate',
                'brand' => 'Norvasc',
                'category' => 'Oral Medications',
                'unit_price' => 22.00,
                'original_price' => null,
                'unit' => 'tablet',
                'available_stock' => 270,
                'description' => 'Calcium channel blocker for hypertension and angina.',
                'rx' => true,
                'badge' => null,
                'rating' => 4.7,
                'sold' => 310,
            ],
            [
                'id' => 16,
                'name' => 'Metformin 500mg Tab',
                'generic_name' => 'Metformin HCl',
                'brand' => 'Glucophage',
                'category' => 'Oral Medications',
                'unit_price' => 15.00,
                'original_price' => null,
                'unit' => 'tablet',
                'available_stock' => 400,
                'description' => 'First-line oral antidiabetic for type 2 diabetes mellitus.',
                'rx' => true,
                'badge' => null,
                'rating' => 4.8,
                'sold' => 390,
            ],
            [
                'id' => 17,
                'name' => 'Losartan 50mg Tab',
                'generic_name' => 'Losartan Potassium',
                'brand' => 'Cozaar',
                'category' => 'Oral Medications',
                'unit_price' => 28.00,
                'original_price' => null,
                'unit' => 'tablet',
                'available_stock' => 0,
                'description' => 'ARB antihypertensive for blood pressure management.',
                'rx' => true,
                'badge' => null,
                'rating' => 4.6,
                'sold' => 210,
            ],
            [
                'id' => 18,
                'name' => 'Dexamethasone 4mg Tab',
                'generic_name' => 'Dexamethasone',
                'brand' => 'Pharex',
                'category' => 'Oral Medications',
                'unit_price' => 20.00,
                'original_price' => null,
                'unit' => 'tablet',
                'available_stock' => 180,
                'description' => 'Corticosteroid for inflammation, allergy, and autoimmune conditions.',
                'rx' => true,
                'badge' => null,
                'rating' => 4.7,
                'sold' => 175,
            ],
            // Wound Care
            [
                'id' => 19,
                'name' => 'Betadine Solution 60mL',
                'generic_name' => 'Povidone-Iodine 10%',
                'brand' => 'Mundipharma',
                'category' => 'Wound Care',
                'unit_price' => 95.00,
                'original_price' => 110.00,
                'unit' => 'bottle',
                'available_stock' => 120,
                'description' => 'Povidone-iodine antiseptic for wound cleaning and disinfection.',
                'rx' => false,
                'badge' => 'SALE',
                'rating' => 4.8,
                'sold' => 340,
            ],
            [
                'id' => 20,
                'name' => 'Sterile Gauze Pads 4x4',
                'generic_name' => 'Gauze Sponge 4x4',
                'brand' => 'Mediline',
                'category' => 'Wound Care',
                'unit_price' => 15.00,
                'original_price' => null,
                'unit' => 'pack',
                'available_stock' => 400,
                'description' => 'Sterile non-woven gauze for wound dressing and absorption.',
                'rx' => false,
                'badge' => null,
                'rating' => 4.8,
                'sold' => 520,
            ],
            [
                'id' => 21,
                'name' => 'Adhesive Bandage Strips',
                'generic_name' => 'Sterile Bandages',
                'brand' => 'Johnson',
                'category' => 'Wound Care',
                'unit_price' => 55.00,
                'original_price' => null,
                'unit' => 'box',
                'available_stock' => 200,
                'description' => 'Flexible waterproof bandage strips for minor cuts and abrasions.',
                'rx' => false,
                'badge' => null,
                'rating' => 4.7,
                'sold' => 410,
            ],
            [
                'id' => 22,
                'name' => 'Surgical Tape 1" x 10yd',
                'generic_name' => 'Micropore Surgical Tape',
                'brand' => '3M',
                'category' => 'Wound Care',
                'unit_price' => 65.00,
                'original_price' => null,
                'unit' => 'roll',
                'available_stock' => 180,
                'description' => 'Hypoallergenic micropore tape for securing dressings.',
                'rx' => false,
                'badge' => null,
                'rating' => 4.6,
                'sold' => 280,
            ],
            [
                'id' => 23,
                'name' => 'Hydrogen Peroxide 3% 120mL',
                'generic_name' => 'Hydrogen Peroxide 3%',
                'brand' => 'Mediline',
                'category' => 'Wound Care',
                'unit_price' => 35.00,
                'original_price' => null,
                'unit' => 'bottle',
                'available_stock' => 250,
                'description' => 'Topical antiseptic for wound cleansing and debridement.',
                'rx' => false,
                'badge' => 'NEW',
                'rating' => 4.5,
                'sold' => 190,
            ],
            // Respiratory
            [
                'id' => 24,
                'name' => 'Salbutamol Nebule 2.5mg',
                'generic_name' => 'Salbutamol Sulfate',
                'brand' => 'Ventolin',
                'category' => 'Respiratory',
                'unit_price' => 28.00,
                'original_price' => null,
                'unit' => 'nebule',
                'available_stock' => 200,
                'description' => 'Short-acting bronchodilator for asthma and COPD exacerbations.',
                'rx' => true,
                'badge' => null,
                'rating' => 4.9,
                'sold' => 360,
            ],
            [
                'id' => 25,
                'name' => 'Ipratropium Nebule 0.5mg',
                'generic_name' => 'Ipratropium Bromide',
                'brand' => 'Atrovent',
                'category' => 'Respiratory',
                'unit_price' => 45.00,
                'original_price' => null,
                'unit' => 'nebule',
                'available_stock' => 150,
                'description' => 'Anticholinergic bronchodilator for COPD management.',
                'rx' => true,
                'badge' => null,
                'rating' => 4.7,
                'sold' => 210,
            ],
            [
                'id' => 26,
                'name' => 'N-Acetylcysteine 200mg',
                'generic_name' => 'Acetylcysteine',
                'brand' => 'Fluimucil',
                'category' => 'Respiratory',
                'unit_price' => 32.00,
                'original_price' => 38.00,
                'unit' => 'sachet',
                'available_stock' => 280,
                'description' => 'Mucolytic agent for productive cough and mucus clearance.',
                'rx' => false,
                'badge' => 'SALE',
                'rating' => 4.6,
                'sold' => 295,
            ],
            // Consumables
            [
                'id' => 27,
                'name' => 'Disposable Syringe 5mL',
                'generic_name' => 'Syringe 5mL with Needle',
                'brand' => 'Terumo',
                'category' => 'Consumables',
                'unit_price' => 12.00,
                'original_price' => null,
                'unit' => 'piece',
                'available_stock' => 1000,
                'description' => 'Sterile single-use syringe for medication administration.',
                'rx' => false,
                'badge' => null,
                'rating' => 4.9,
                'sold' => 1800,
            ],
            [
                'id' => 28,
                'name' => 'IV Cannula G18',
                'generic_name' => 'IV Catheter 18G',
                'brand' => 'Terumo',
                'category' => 'Consumables',
                'unit_price' => 28.00,
                'original_price' => null,
                'unit' => 'piece',
                'available_stock' => 500,
                'description' => 'Peripheral IV catheter for intravenous access.',
                'rx' => false,
                'badge' => null,
                'rating' => 4.8,
                'sold' => 920,
            ],
            [
                'id' => 29,
                'name' => 'Nitrile Gloves (M) Box/100',
                'generic_name' => 'Exam Gloves Medium',
                'brand' => 'Medline',
                'category' => 'Consumables',
                'unit_price' => 320.00,
                'original_price' => 380.00,
                'unit' => 'box',
                'available_stock' => 150,
                'description' => 'Powder-free nitrile examination gloves for clinical use.',
                'rx' => false,
                'badge' => 'SALE',
                'rating' => 4.8,
                'sold' => 680,
            ],
            [
                'id' => 30,
                'name' => 'Surgical Mask Box/50',
                'generic_name' => 'Medical Mask 3-Ply',
                'brand' => '3M',
                'category' => 'Consumables',
                'unit_price' => 185.00,
                'original_price' => null,
                'unit' => 'box',
                'available_stock' => 200,
                'description' => '3-ply surgical mask for infection prevention.',
                'rx' => false,
                'badge' => null,
                'rating' => 4.7,
                'sold' => 750,
            ],
            [
                'id' => 31,
                'name' => 'Nasogastric Tube Fr14',
                'generic_name' => 'NG Tube Fr14',
                'brand' => 'Covidien',
                'category' => 'Consumables',
                'unit_price' => 85.00,
                'original_price' => null,
                'unit' => 'piece',
                'available_stock' => 80,
                'description' => 'Flexible tube for enteral feeding and gastric decompression.',
                'rx' => false,
                'badge' => null,
                'rating' => 4.6,
                'sold' => 95,
            ],
            [
                'id' => 32,
                'name' => 'Urine Drainage Bag 2L',
                'generic_name' => 'Urine Bag 2000mL',
                'brand' => 'Covidien',
                'category' => 'Consumables',
                'unit_price' => 75.00,
                'original_price' => null,
                'unit' => 'piece',
                'available_stock' => 120,
                'description' => 'Sterile closed urine collection system for catheterized patients.',
                'rx' => false,
                'badge' => null,
                'rating' => 4.7,
                'sold' => 140,
            ],
            // Supplements
            [
                'id' => 33,
                'name' => 'Vitamin C 500mg Tab',
                'generic_name' => 'Ascorbic Acid',
                'brand' => 'Ascorbicap',
                'category' => 'Supplements',
                'unit_price' => 5.00,
                'original_price' => null,
                'unit' => 'tablet',
                'available_stock' => 800,
                'description' => 'Ascorbic acid for immune support and antioxidant therapy.',
                'rx' => false,
                'badge' => null,
                'rating' => 4.9,
                'sold' => 1100,
            ],
            [
                'id' => 34,
                'name' => 'Vitamin B Complex Tab',
                'generic_name' => 'B-Complex Vitamins',
                'brand' => 'Neurobion',
                'category' => 'Supplements',
                'unit_price' => 18.00,
                'original_price' => null,
                'unit' => 'tablet',
                'available_stock' => 500,
                'description' => 'B-vitamin complex for neurological support and metabolism.',
                'rx' => false,
                'badge' => null,
                'rating' => 4.8,
                'sold' => 640,
            ],
            [
                'id' => 35,
                'name' => 'Zinc Sulfate 20mg Tab',
                'generic_name' => 'Zinc Sulfate Monohydrate',
                'brand' => 'Pharex',
                'category' => 'Supplements',
                'unit_price' => 7.00,
                'original_price' => null,
                'unit' => 'tablet',
                'available_stock' => 400,
                'description' => 'Essential mineral for immune function and wound healing.',
                'rx' => false,
                'badge' => 'NEW',
                'rating' => 4.7,
                'sold' => 380,
            ],
        ];

        // Overlay with any live database medicines if available
        $items = collect($figmaCatalog);
        foreach ($dbMedicines as $dbMed) {
            $existingIndex = $items->search(function ($item) use ($dbMed) {
                return strtolower(trim($item['name'])) === strtolower(trim($dbMed->name))
                    || (isset($dbMed->generic_name) && strtolower(trim($item['generic_name'])) === strtolower(trim($dbMed->generic_name)));
            });

            if ($existingIndex !== false) {
                $item = $items->get($existingIndex);
                $item['available_stock'] = $dbMed->available_stock;
                $item['unit_price'] = (float) $dbMed->unit_price;
                $items->put($existingIndex, $item);
            }
        }

        return $items;
    }
}
